# Generated by Django 5.1.3 on 2025-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_papad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_1kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_500g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_250g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='snacks_images/')),
            ],
        ),
    ]
