# Generated by Django 5.1.3 on 2025-02-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_pickle_price_1kg_remove_pickle_price_250g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickle',
            name='video',
        ),
        migrations.AddField(
            model_name='pickle',
            name='price_1kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pickle',
            name='price_250g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pickle',
            name='price_500g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pickle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
