# Generated by Django 5.1.3 on 2025-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price_1kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_500g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_250g', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
