# Generated by Django 5.1.3 on 2025-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickle',
            name='price_1kg',
        ),
        migrations.RemoveField(
            model_name='pickle',
            name='price_250g',
        ),
        migrations.RemoveField(
            model_name='pickle',
            name='price_500g',
        ),
        migrations.AddField(
            model_name='pickle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pickles/videos/'),
        ),
        migrations.AlterField(
            model_name='pickle',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
